#!/usr/bin/env bash
# A script to provide information about subdomain related to a specific domain
# Usage: ./0-world_wide_web domain
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
# Usage: ./0-world_wide_web domain [subdomain]
# Output: The subdomain [subdomain] is a [RECORD_TYPE] record and points to [DESTINATION]

if [ "$#" -lt 1 ]
then
	exit 1
elif [ "$#" -eq 1 ]
then
	www="www"
	lb_01="lb-01"
	web_01="web-01"
	web_02="web-02"
	for i in $www $lb_01 $web_01 $web_02
	do
		record_type=$(dig $i.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
		destination=$(dig $i.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
		echo The subdomain $i is a $record_type record and points to $destination
	done
else
	record_type=$(dig $2.$1 +noall +answer | awk '{print $4}')
	destination=$(dig $2.$1 +noall +answer | awk '{print $5}')
	echo The subdomain $2 is a $record_type record and points to $destination
fi
