#!/usr/bin/env bash
# A bash script to transfer a file to a server. File path,
# server ip address, username to connect as and optionally
# ssh identity file are passed as command line arguments.
# The file is sent to the target server home directory

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	filename="${1##*/}"
	if [ "$#" -eq 4 ]
	then
		scp -o StrictHostKeyChecking=no "-i $4" "$1" "$3@$2:~/$filename"
	else
		scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/$filename"
	fi
fi
