#!/usr/bin/env bash
# A bash script to install and configure "Nginx" web server to return
# a webpage containing the statement "Hello, World!"

apt-get -y install nginx
rm /var/www/html/*
echo "Hello World!" > /var/www/html/index.html
nginx
