#!/usr/bin/env bash
# A bash script to configure Nginx to return a custom 404 error page

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
lines="server_name _;\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -i "s|server_name _;|$lines|g" /etc/nginx/sites-available/default
nginx -t
nginx -s reload
