#!/usr/bin/env bash
# A script to install and configure HAprxoy load balancer on "Ubuntu 16.04 LTS"
# to handle traffic to the servers 54.208.189.21 and 54.87.253.151

frontend="\nfrontend my_front_end\n\tbind *:80\n\tdefault_backend my_back_end"
backend="\nbackend my_back_end\n\tserver server1 54.208.189.21:80\n\tserver server2 54.87.253.151:80"

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*

echo -e "$frontend" >> /etc/haproxy/haproxy.cfg
echo -e "$backend" >> /etc/haproxy/haproxy.cfg
pkill -SIGUSR2 haproxy
