#!/usr/bin/env bash
# A script to make a backup from all the databases in the current server.
# Usage: ./5-mysql_backup PASSWORD

mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date +%d-%m-%Y)".tar.gz backup.sql

