#!/usr/bin/env bash
# This is a bash script for printing "Best School" 10 times and "Hi" once

i=0

while [ "$i" -lt 10 ]; do
  if [ "$i" = 8 ]
  then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi
  i=$((i + 1))
done
