#!/usr/bin/env bash
# This is a bash script for applying "if", "elif" and "else" concept"

i=0

while [ "$i" -lt 10 ]; do
  if [ "$i" = 3 ]
  then
    echo -e "bad luck"
  elif [ "$i" = 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  i=$((i + 1))
done
