#!/usr/bin/env bash
# This is a script to change "localhost" and "facebook.com"
# resolution addresses on the "/etc/hosts" file
cp /etc/hosts ~/hosts.new
sed -i s/'127.0.0.1'/'127.0.0.2'/g ~/hosts.new
sed -i s/'157.240.11.35'/'8.8.8.8'/g ~/hosts.new
cat ~/hosts.new > /etc/hosts
rm ~/hosts.new
