#!/usr/bin/env bash
# root script to execute a command as another user

users="$(cut -d : -f 1 < /etc/passwd)"
user="$1"

for _ in $users
do
	if [ "$_" == "$user" ]
	then
		fifth="$(grep "$user" /etc/passwd | cut -d : -f 5)"
		if [ -n "$fifth" ]
		then
			su -c whoami "$user"
		else
			echo "$user"
		fi
	fi
done
